name: novel_day
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  lottie: ^3.2.0
  shared_preferences: ^2.2.3
  purchases_flutter: ^8.4.0
  google_mobile_ads: ^5.0.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/writing_book1.json
    - assets/lottie/writing_book2.json
    - assets/book_shelf.png
    - assets/book_original.png
    - assets/icon.png
    - assets/icon_opening.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true